apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  nodeSelector:
    node: yunni-desktop   # ← 사용자가 말한 라벨 key=value 그대로
  containers:
  - name: counter
    image: yunniverse/counter:0.2
    command: ["sh","-c","sleep infinity"]
  restartPolicy: Always
