apiVersion: v1
kind: ServiceAccount
metadata:
  name: coz
  namespace: mcoz-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coz-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]
    resources: ["globaldelays"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coz-pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coz-pod-reader
subjects:
  - kind: ServiceAccount
    name: coz
    namespace: mcoz-system
