apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: mcoz-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      nodeSelector:
        node: yunni-desktop
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sleep", "3600"]

